#!/bin/bash
# Copyright (c) 2016 Akuli
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# This script ask a directory from the user and writes it to
# prefix-selection in the current directory.

echo ""
echo "Where would you like to install this program?"
echo "Enter an absolute path that does not end with a slash."

while true
do
	read path
	length="${#path}"
	((length--))
	first_char="${path:0:1}"
	last_char="${path:$length:1}"
	if [ "$first_char" = "/" ] && [ "$last_char" != "/" ] && [ -d "$path" ]
	then
		break
	else
		echo "'$path' is not a valid path."
	fi
done

echo "$path" > prefix-selection
echo "The prefix was changed."
